// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'datum.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Datum _$DatumFromJson(Map<String, dynamic> json) => Datum(
      videoId: json['videoId'] as int?,
      userId: json['userId'] as int?,
      courseId: json['courseId'] as int?,
      videoTitle: json['videoTitle'] as String?,
      videoKey: json['videoKey'] as String?,
      bucket: json['bucket'] as String?,
      coordinate: json['coordinate'] as String?,
      address: json['address'] as String?,
      cityCode: json['cityCode'] as int?,
      privacyType: json['privacyType'] as int?,
      widtheight: json['widtheight'] as String?,
      isDownload: json['isDownload'] as int?,
      resources: json['resources'] as String?,
      cover: json['cover'] as String?,
      coverMiniUrl: json['coverMiniUrl'] as String?,
      state: json['state'] as int?,
      isDel: json['isDel'] as int?,
      auditState: json['auditState'] as int?,
      collectionId: json['collectionId'] as int?,
      releaseTime: json['releaseTime'] as String?,
      createdAt: json['createdAt'] as String?,
      weight: json['weight'] as int?,
      head: json['head'] as String?,
      account: json['account'] as String?,
      nickname: json['nickname'] as String?,
      mark: json['mark'] as int?,
      identity: json['identity'] as List<dynamic>?,
      isFocus: json['isFocus'] as bool?,
      isPraised: json['isPraised'] as bool?,
      courseLabel: json['courseLabel'] as String?,
      traceId: json['traceId'] as String?,
      traceInfo: json['traceInfo'] as String?,
      collectionTitle: json['collectionTitle'] as String?,
      orderType: json['orderType'] as int?,
      intMerchantId: json['intMerchantId'] as int?,
      intMerchantUserId: json['intMerchantUserId'] as int?,
      goodsInfo: json['goodsInfo'] == null
          ? null
          : GoodsInfo.fromJson(json['goodsInfo'] as Map<String, dynamic>),
      url: json['url'] as String?,
      commentCount: json['commentCount'] as int?,
      isFirstComment: json['isFirstComment'] as bool?,
      praisedCount: json['praisedCount'] as int?,
      playCount: json['playCount'] as int?,
      shareCount: json['shareCount'] as int?,
      videoTime: json['videoTime'] as int?,
      hot: json['hot'] as int?,
      liveId: json['liveId'] as int?,
      liveNo: json['liveNo'] as String?,
      type: json['type'] as int?,
      isOnlineLive: json['isOnlineLive'] as bool?,
    );

Map<String, dynamic> _$DatumToJson(Datum instance) => <String, dynamic>{
      'videoId': instance.videoId,
      'userId': instance.userId,
      'courseId': instance.courseId,
      'videoTitle': instance.videoTitle,
      'videoKey': instance.videoKey,
      'bucket': instance.bucket,
      'coordinate': instance.coordinate,
      'address': instance.address,
      'cityCode': instance.cityCode,
      'privacyType': instance.privacyType,
      'widtheight': instance.widtheight,
      'isDownload': instance.isDownload,
      'resources': instance.resources,
      'cover': instance.cover,
      'coverMiniUrl': instance.coverMiniUrl,
      'state': instance.state,
      'isDel': instance.isDel,
      'auditState': instance.auditState,
      'collectionId': instance.collectionId,
      'releaseTime': instance.releaseTime,
      'createdAt': instance.createdAt,
      'weight': instance.weight,
      'head': instance.head,
      'account': instance.account,
      'nickname': instance.nickname,
      'mark': instance.mark,
      'identity': instance.identity,
      'isFocus': instance.isFocus,
      'isPraised': instance.isPraised,
      'courseLabel': instance.courseLabel,
      'traceId': instance.traceId,
      'traceInfo': instance.traceInfo,
      'collectionTitle': instance.collectionTitle,
      'orderType': instance.orderType,
      'intMerchantId': instance.intMerchantId,
      'intMerchantUserId': instance.intMerchantUserId,
      'goodsInfo': instance.goodsInfo,
      'url': instance.url,
      'commentCount': instance.commentCount,
      'isFirstComment': instance.isFirstComment,
      'praisedCount': instance.praisedCount,
      'playCount': instance.playCount,
      'shareCount': instance.shareCount,
      'videoTime': instance.videoTime,
      'hot': instance.hot,
      'liveId': instance.liveId,
      'liveNo': instance.liveNo,
      'type': instance.type,
      'isOnlineLive': instance.isOnlineLive,
    };
