# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auto_Package' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Auto_Package
  pod 'YYText', '~> 1.0.7'
end
