# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!
target 'Day4_RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Day4_RxSwift

    pod 'RxSwift', '5.0.0'
    pod 'RxCocoa', '5.0.0'
end
